### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by solomonshalom** [peterdev22/peterkni.com#1]
HI!

I tried checking out the website but it's showing me a "500 Error" when I open it up 🤔 

Wanted to bring it to your attention!

**Comment by peterdev22** [comment]
Hey, thanks for letting me know!

I just tested the website on a few different web browsers and it seems to be working.

I did a big update on its layout just a few weeks ago so maybe the server-side cache is clashing with the new content. I'll reset it just to make sure that is not the issue.

If you still wanna have a look and its not working, let me know, and i'll try something else. Thanks.

**Comment by solomonshalom** [comment]
> Hey, thanks for letting me know!
> 
> I just tested the website on a few different web browsers and it seems to be working.
> 
> I did a big update on its layout just a few weeks ago so maybe the server-side cache is clashing with the new content. I'll reset it just to make sure that is not the issue.
> 
> If you still wanna have a look and its not working, let me know, and i'll try something else. Thanks.

Hi!

It works perfectly now!

Really cool site but I had a Q, which is was it intentionally designed so that when you scrolled down - you could not scroll to the top unless you reload the site?

When I tried scrolling up, it started moving the cards displayed in a right direction 🤔 

In any case, really cool site!

**Comment by peterdev22** [comment]
Thanks so much I really appreciate it, I'm glad you like the site!

> Really cool site but I had a Q, which is was it intentionally designed so that when you scrolled down - you could not scroll to the top unless you reload the site?
> 
> When I tried scrolling up, it started moving the cards displayed in a right direction 🤔

I think that might be happening due to using normal scroll when the screen width is small enough but then reverting to the custom side scroll when the window is wide enough again.

It could be fixed by reseting the scroll back to the top when the switching between the two scroll types so i'll definitely give it a try.

**Comment by peterdev22** [comment]
Fixed a few issues relating to window resizing and the website getting stuck trying to scroll in a48f0bc.

If you're still having the issue just let me know 👍.
